name: eslint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm.v0..38.0/install.sh | bash
      - name: Install NodeJS
        env:
          NODE_VERSION: 14.17.0
        run: nvm install $NODE_VERSION
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '14'
      # - run: npm run docker:test
